{% set name = "felyx-processor" %}
{% set version = "2.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/felyx/felyx_processor/-/archive/{{ version }}/felyx_processor-{{ version }}.tar.gz
  sha256: bde701ac5c18953cefe59eefe4afdc198f3f826ab0f85847c39f65e253718fc8

build:
  script_env:
    - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
  script:
    - GIT_LFS_SKIP_SMUDGE=1
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - felyx-extraction = felyx_processor.main.miniprod:felyx_miniprod
    - felyx-install = felyx_processor.main.install:main
    - felyx-assemble = felyx_processor.main.matchups:assemble_matchups
    - felyx-metric = felyx_processor.main.metric:felyx_metric
    - felyx-wipe-miniprods = felyx_processor.main.wipe_miniprods:wipe_miniprods
    - felyx-convert-site-data = felyx_processor.main.dynamicsites:convert
    - felyx-register-metrics = felyx_processor.main.register_metrics:felyx_register_metrics
    - felyx-register-miniprods = felyx_processor.main.register_miniprods:felyx_register_miniprods
    - felyx-get-trajectories = felyx_processor.main.get_trajectories:felyx_get_trajectories
    - felyx-get-raws = felyx_processor.main.get_raws:felyx_get_raws
    - felyx-get-coverage = felyx_processor.main.get_coverage:felyx_get_coverage
    - felyx-import-parquet-insitu = felyx_processor.main.import_parquet_insitu:felyx_import_parquet_insitu
    - felyx-get-metrics = felyx_processor.main.get_metrics:felyx_get_metrics
    - felyx-collect-eo-files = felyx_processor.main.collect_eo_files:felyx_collect_eo_files


requirements:
  host:
    - python>=3.10,<3.11
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
      - python>=3.10,<3.11
      - pip
      - Cython==3.0.11
      - elasticsearch==7.17.0
      - numexpr==2.10.2
      - pyarrow>=17.0,<18.0
      - pydantic==2.9.1
      - pyresample==1.31.0
      - pyyaml==6.0.2
      - requests>=2.32.3
      - scipy==1.14.1
      - shapely==2.0.6
      - simplejson==3.19.3
      - pyinterp==2024.11.0
      - polygon-geohasher==0.0.1

test:
  imports:
    - felyx_processor

about:
  home: https://gitlab.ifremer.fr/felyx/felyx_processor
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: felyx is a free software solution, written in python, whose aim is to provide Earth Observation data producers and users with an open-source, flexible and reusable tool to allow scientific analysis and performance monitoring of scientific observation data through subsetting over specific areas or matching up with in situ measurements.

extra:
  recipe-maintainers:
    - criou-cg
    - cso2943
    - erwanbodere
    - marie59
